// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZulaMed.API.Data;

#nullable disable

namespace ZulaMed.API.Data.Migrations
{
    [DbContext(typeof(ZulaMedDbContext))]
    [Migration("20230920201435_AddHistoryPausedToUser")]
    partial class AddHistoryPausedToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlaylistVideo", b =>
                {
                    b.Property<Guid>("PlaylistsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VideosId")
                        .HasColumnType("uuid");

                    b.HasKey("PlaylistsId", "VideosId");

                    b.HasIndex("VideosId");

                    b.ToTable("PlaylistVideo");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RelatedVideoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SentById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RelatedVideoId");

                    b.HasIndex("SentById");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Comments.Reply", b =>
                {
                    b.Property<Guid>("ParentCommentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReplyCommentId")
                        .HasColumnType("uuid");

                    b.HasKey("ParentCommentId", "ReplyCommentId");

                    b.HasIndex("ReplyCommentId");

                    b.ToTable("Reply");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Dislike.Dislike<ZulaMed.API.Domain.Video.Video>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DislikedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DislikedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "ParentId", "DislikedById");

                    b.HasIndex("DislikedById");

                    b.HasIndex("ParentId");

                    b.ToTable("Dislike<Video>");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Like.Like<ZulaMed.API.Domain.Video.Video>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LikedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id", "ParentId", "LikedById");

                    b.HasIndex("LikedById");

                    b.HasIndex("ParentId");

                    b.ToTable("Like<Video>");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Playlist.Playlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlaylistDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlaylistName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.SpecialtyGroup.SpecialtyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecialtyGroup");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscribedToId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriberId", "SubscribedToId");

                    b.HasIndex("SubscribedToId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("HistoryPaused")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkPlace")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Video.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VideoDislike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("VideoLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("VideoPublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoThumbnail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("VideoView")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.ViewHistory.ViewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ViewedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ViewedVideoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViewedById");

                    b.HasIndex("ViewedVideoId");

                    b.ToTable("ViewHistory");
                });

            modelBuilder.Entity("PlaylistVideo", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.Playlist.Playlist", null)
                        .WithMany()
                        .HasForeignKey("PlaylistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.Video.Video", null)
                        .WithMany()
                        .HasForeignKey("VideosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Comments.Comment", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.Video.Video", "RelatedVideo")
                        .WithMany("Comments")
                        .HasForeignKey("RelatedVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.User.User", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedVideo");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Comments.Reply", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.Comments.Comment", "ParentComment")
                        .WithMany()
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.Comments.Comment", "ReplyComment")
                        .WithMany()
                        .HasForeignKey("ReplyCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentComment");

                    b.Navigation("ReplyComment");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Dislike.Dislike<ZulaMed.API.Domain.Video.Video>", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.User.User", "DislikedBy")
                        .WithMany()
                        .HasForeignKey("DislikedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.Video.Video", "Parent")
                        .WithMany("Dislikes")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DislikedBy");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Like.Like<ZulaMed.API.Domain.Video.Video>", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.User.User", "LikedBy")
                        .WithMany()
                        .HasForeignKey("LikedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.Video.Video", "Parent")
                        .WithMany("Likes")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LikedBy");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Playlist.Playlist", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.User.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Subscriptions.Subscription", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.User.User", "SubscribedTo")
                        .WithMany("Subscribers")
                        .HasForeignKey("SubscribedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.User.User", "Subscriber")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubscribedTo");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.User.User", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.SpecialtyGroup.SpecialtyGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Video.Video", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.User.User", "Publisher")
                        .WithMany("Videos")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.ViewHistory.ViewHistory", b =>
                {
                    b.HasOne("ZulaMed.API.Domain.User.User", "ViewedBy")
                        .WithMany()
                        .HasForeignKey("ViewedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZulaMed.API.Domain.Video.Video", "ViewedVideo")
                        .WithMany("ViewHistories")
                        .HasForeignKey("ViewedVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ViewedBy");

                    b.Navigation("ViewedVideo");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.User.User", b =>
                {
                    b.Navigation("Subscribers");

                    b.Navigation("Subscriptions");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ZulaMed.API.Domain.Video.Video", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Dislikes");

                    b.Navigation("Likes");

                    b.Navigation("ViewHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
